//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGRE.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int idreport { get; set; }
        public int idUser { get; set; }
        public System.DateTime dateReport { get; set; }
        public int idMarket { get; set; }
        public int idSample { get; set; }
        public Nullable<int> idUbigeo { get; set; }
    
        public virtual Market Market { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        public virtual Sample Sample { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
